-- Create the todos table
create table public.todos (
    id bigint generated by default as identity primary key,
    title text not null,
    status text not null default 'Todo',
    priority text not null default 'Medium',
    type text not null default 'Feature',
    user_id uuid references auth.users not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Add constraints for status, priority and type
    constraint valid_status check (status in ('Todo', 'In Progress', 'Done', 'Backlog', 'Cancelled')),
    constraint valid_priority check (priority in ('Low', 'Medium', 'High')),
    constraint valid_type check (type in ('Feature', 'Bug', 'Documentation'))
);

-- Enable Row Level Security (RLS)
alter table public.todos enable row level security;

-- Create policies
-- Allow users to select only their own todos
create policy "Users can view their own todos"
    on public.todos for select
    using (auth.uid() = user_id);

-- Allow users to insert their own todos
create policy "Users can create their own todos"
    on public.todos for insert
    with check (auth.uid() = user_id);

-- Allow users to update their own todos
create policy "Users can update their own todos"
    on public.todos for update
    using (auth.uid() = user_id);

-- Allow users to delete their own todos
create policy "Users can delete their own todos"
    on public.todos for delete
    using (auth.uid() = user_id);

-- Create indexes for better performance
create index todos_user_id_idx on public.todos(user_id);
create index todos_created_at_idx on public.todos(created_at);

-- Create a function to automatically update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Create a trigger to automatically update updated_at
create trigger handle_updated_at
    before update on public.todos
    for each row
    execute function public.handle_updated_at(); 